Repository martipal/SoundBubble, pull requests merged in 2019-07, with the labels that each got.

#18 Implemented create/add/leave group
  sound-bubble/imports/ui/actions/groupActions.js
  sound-bubble/imports/ui/components/About/About.jsx
  sound-bubble/imports/ui/components/Groups/Group.jsx
  sound-bubble/imports/ui/components/Groups/GroupMember.jsx
  sound-bubble/imports/ui/components/Groups/Groups.jsx
  sound-bubble/imports/ui/stylesheets/Groups.css
  sound-bubble/server/main.js
  sound-bubble/server/methods/commonMethods.js
  sound-bubble/server/methods/groupMethods.js
Labels: bug, enhancement

#20 Remove insecure and autopublish
  sound-bubble/.meteor/packages
  sound-bubble/.meteor/versions
  sound-bubble/imports/ui/actions/accountActions.js
  sound-bubble/imports/ui/components/Account/HideSongButton.jsx
  sound-bubble/imports/ui/components/Account/User.jsx
  sound-bubble/imports/ui/components/Account/UserFeed.jsx
  sound-bubble/imports/ui/components/Groups/Group.jsx
  sound-bubble/imports/ui/components/Groups/GroupMember.jsx
  sound-bubble/imports/ui/components/Groups/Groups.jsx
  sound-bubble/imports/ui/components/Home/GroupButton.jsx
  sound-bubble/imports/ui/components/Home/SongLog.jsx
  sound-bubble/imports/ui/components/Home/Vote.jsx
  sound-bubble/imports/ui/components/Song.jsx
  sound-bubble/server/methods/accountMethods.js
  sound-bubble/server/methods/groupMethods.js
  sound-bubble/server/publication.js
Labels: enhancement

#22 Styling on All Pages
  sound-bubble/imports/ui/components/About/About.jsx
  sound-bubble/imports/ui/components/About/DeveloperInfo.jsx
  sound-bubble/imports/ui/components/Account/Account.jsx
  sound-bubble/imports/ui/components/Account/User.jsx
  sound-bubble/imports/ui/components/Account/UserFeed.jsx
  sound-bubble/imports/ui/components/AppRouter.jsx
  sound-bubble/imports/ui/components/Groups/Group.jsx
  sound-bubble/imports/ui/components/Groups/GroupMember.jsx
  sound-bubble/imports/ui/components/Groups/Groups.jsx
  sound-bubble/imports/ui/components/Home/GroupButton.jsx
  sound-bubble/imports/ui/components/Home/Home.jsx
  sound-bubble/imports/ui/components/Home/SongLog.jsx
  sound-bubble/imports/ui/components/Home/Vote.jsx
  sound-bubble/imports/ui/components/Song.jsx
  sound-bubble/imports/ui/stylesheets/About.css
  sound-bubble/imports/ui/stylesheets/Account.css
  sound-bubble/imports/ui/stylesheets/Groups.css
  sound-bubble/imports/ui/stylesheets/Heading.css
  sound-bubble/imports/ui/stylesheets/main.css
Labels: enhancement

#23 searchUser, addUser, vote refine
  sound-bubble/imports/ui/actions/groupActions.js
  sound-bubble/imports/ui/components/Groups/Group.jsx
  sound-bubble/imports/ui/components/Groups/Search.jsx
  sound-bubble/imports/ui/stylesheets/Groups.css
  sound-bubble/server/methods/groupMethods.js
  sound-bubble/server/publication.js
Labels: enhancement

#21 Get song logs from db instead of redux store
  sound-bubble/.meteor/packages
  sound-bubble/.meteor/versions
  sound-bubble/imports/ui/actions/accountActions.js
  sound-bubble/imports/ui/actions/homeActions.js
  sound-bubble/imports/ui/components/Account/HideSongButton.jsx
  sound-bubble/imports/ui/components/Account/UserFeed.jsx
  sound-bubble/imports/ui/components/Home/SongLog.jsx
  sound-bubble/imports/ui/components/Home/Vote.jsx
  sound-bubble/imports/ui/components/Song.jsx
  sound-bubble/imports/ui/reducers/currentGroupReducer.jsx
  sound-bubble/imports/ui/reducers/index.js
  sound-bubble/imports/ui/reducers/songLogReducer.jsx
  sound-bubble/server/methods/accountMethods.js
  sound-bubble/server/methods/commonMethods.js
  sound-bubble/server/methods/homeMethods.js
  sound-bubble/server/publication.js
Labels: enhancement

#25 remove group bug fix
  sound-bubble/imports/ui/actions/groupActions.js
  sound-bubble/imports/ui/reducers/index.js
Labels: bug

#34 Bug fix: Update and get the correct token from db
  sound-bubble/imports/ui/components/Account/UserFeed.jsx
  sound-bubble/imports/ui/components/Home/GroupButton.jsx
  sound-bubble/imports/ui/components/Home/SongLog.jsx
  sound-bubble/server/methods/commonMethods.js
  sound-bubble/server/methods/homeMethods.js
  sound-bubble/server/spotify-api.js
Labels: bug

#36 Logout Button
  sound-bubble/imports/ui/components/Account/AccountsUIWrapper.jsx
  sound-bubble/imports/ui/components/Account/User.jsx
Labels: bug

#37 Styling misc
  sound-bubble/imports/ui/components/Account/HideSongButton.jsx
  sound-bubble/imports/ui/components/Account/User.jsx
  sound-bubble/imports/ui/components/Groups/Group.jsx
  sound-bubble/imports/ui/components/Groups/Groups.jsx
  sound-bubble/imports/ui/components/Groups/Search.jsx
  sound-bubble/imports/ui/stylesheets/Account.css
  sound-bubble/imports/ui/stylesheets/Groups.css
  sound-bubble/imports/ui/stylesheets/main.css
Labels: enhancement

#38 group method enhanced
  sound-bubble/imports/api/groups.js
  sound-bubble/imports/ui/actions/groupActions.js
  sound-bubble/imports/ui/components/Account/User.jsx
  sound-bubble/imports/ui/components/Groups/Group.jsx
  sound-bubble/imports/ui/components/Groups/GroupMember.jsx
  sound-bubble/imports/ui/components/Groups/Groups.jsx
  sound-bubble/package-lock.json
  sound-bubble/server/methods/groupMethods.js
Labels: enhancement

#40 Properly decrement vote when user changes vote
  sound-bubble/imports/ui/components/Home/Vote.jsx
  sound-bubble/server/methods/homeMethods.js
Labels: bug

#39 Clean up code
  sound-bubble/.meteor/packages
  sound-bubble/.meteor/versions
  sound-bubble/imports/ui/components/Account/UserFeed.jsx
  sound-bubble/imports/ui/components/Groups/GroupMember.jsx
  sound-bubble/imports/ui/components/Home/Vote.jsx
  sound-bubble/imports/ui/components/Song.jsx
  sound-bubble/imports/ui/stylesheets/Account.css
  sound-bubble/imports/ui/stylesheets/main.css
  sound-bubble/package-lock.json
  sound-bubble/server/spotify-api.js
Labels: enhancement
